[package]
name = "mar-21"
version = "0.1.0"
authors = ["Andrew <cotter.andrew.p@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = {git = "https://github.com/nannou-org/nannou"}
